default: testacc

.PHONY: generate
generate:
	go generate ./...

# Run acceptance tests
.PHONY: testacc
testacc: generate lint
	TF_ACC=1 go test ./... -v $(TESTARGS) -coverprofile=coverage.out -timeout 120m

# Run acceptance tests and show coverages
.PHONY: testacc-cover
testacc-cover: testacc
	go tool cover -func=coverage.out
	go tool cover -html=coverage.out


.PHONY: lint
lint:
	@golangci-lint run

.PHONY: fmt
fmt:
	go fmt ./...
	terraform fmt --recursive

.PHONY: fmt-check
fmt-check: fmt
	@if [ "`git status --porcelain `" ]; then \
	  echo "Uncommitted changes were detected in the autogenerated docs folder. Please run 'make fmt' to autogenerate the docs, and commit the changes" && echo `git status --porcelain docs/` && exit 1; \
	fi

.PHONY: docs-check
docs-check: generate
	@if [ "`git status --porcelain docs/`" ]; then \
	  echo "Uncommitted changes were detected in the autogenerated docs folder. Please run 'make generate' to autogenerate the docs, and commit the changes" && echo `git status --porcelain docs/` && exit 1; \
	fi